name: Deploy My Web Server

on:
  push:
    branches:
      - master # 只在master上push触发部署

jobs:
  deploy:
    runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本

    steps: # 自动化步骤
      #下载代码仓库
      - uses: actions/checkout@v3

      # 使用action库，安装node
      - name: use Node.js # 使用action库  actions/setup-node安装node
        uses: actions/setup-node@v3

      # 安装依赖
      - name: npm install
        run: cd ./web && ls && npm install --legacy-peer-deps

      #打包项目
      - name: Build
        run: cd ./web && npm run build

      #部署到服务器
      - name: Deploy to Staging My server
        uses: easingthemes/ssh-deploy@v2.1.6
        env:
          #私钥
          SSH_PRIVATE_KEY: ${{ secrets.MY_SERVER_PRIVATE_KEY }} #后面指定为该仓库配置的私钥
          ARGS: -rltgoDzvO --delete
          # 源目录，编译后生成的文件目录
          SOURCE: ./web/
          #服务器公网地址
          REMOTE_HOST: ${{ secrets.SSH_HOST }}
          #服务器用户名-一般默认root
          REMOTE_USER: ${{ secrets.SSH_USERNAME }}
          #服务器中，代码部署的位置
          TARGET: /home/blogWeb/
          #包含的文件
          EXCLUDE: /node_modules/

      - name: Reload Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/blogWeb/
            npm install --legacy-peer-deps
            pm2 reload ecosystem.config.js
