name: Blog Web CI # Actions名称

on: # 执行时机
  push:
    branches:
      - master

jobs:
  build:
    # runs-on 指定job任务运行所需要的虚拟机环境(必填字段)
    runs-on: ubuntu-latest
    steps:
      # 拉取代码
      - name: Checkout # 步骤名字
        # 使用action库  actions/checkout拉取源码
        uses: actions/checkout@master

      # 安装依赖
      - name: Install
        run: cd ./web && ls && npm install --legacy-peer-deps

      # 打包
      - name: Build Project
        run: cd ./web && ls && npm run build

      # 生成 Release
      - name: Build Release
        uses: actions/setup-node@master
      - run: cd ./web  && tar -zcvf release-web.tgz .output .nuxt public nuxt.config.ts package.json package-lock.json ecosystem.config.js && ls

        # 发布 Release
      - name: Create Release
        id: create_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: Tag ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # 上传构建结果到 Release
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./web/release-web.tgz
          asset_name: release-web.tgz
          asset_content_type: application/x-tgz

      # 部署到服务器
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd /home/blogWeb/
            wget https://github.com/jc9135/MyBlogProject/web/ -O release-web.tgz
            tar zxvf release-web.tgz
            npm install --legacy-peer-deps
            pm2 reload ecosystem.config.js
